window:
  opacity: 1

  title: terminal

  padding:
    x: 40
    y: 20

  dimensions:
    columns: 40
    lines: 10

font:
  normal:
    family: Iosevka Nerd Font
    style: Medium

  bold:
    family: Iosevka Nerd Font
    style: Bold

  size: 9.0

colors:
  primary:
    background: '#ffffff'
    foreground: '#101010'
  cursor:
    text:   CellForeground
    cursor: '#101010'
  bright:
    black:   '#101010'
    red:     '#fc7b81'
    green:   '#94f7c5'
    yellow:  '#ffeba6'
    blue:    '#8cc1ff'
    magenta: '#e2a6ff'
    cyan:    '#90daff'
    white:   '#101010'
  normal:
    black:   '#fefefe'
    red:     '#e05f65'
    green:   '#78dba9'
    yellow:  '#f1cf8a'
    blue:    '#70a5eb'
    magenta: '#c68aee'
    cyan:    '#74bee9'
    white:   '#101010'

cursor:
  style: Beam
